# Generated by Django 4.1.2 on 2022-11-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
                ('position', models.CharField(max_length=3)),
                ('player_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=40)),
                ('opponent', models.CharField(max_length=40)),
                ('result', models.CharField(default='0-0', max_length=7)),
                ('info', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_ball', models.SmallIntegerField()),
                ('goals', models.SmallIntegerField()),
                ('assists', models.SmallIntegerField()),
                ('points', models.SmallIntegerField()),
                ('face_offs', models.SmallIntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='byulax.schedule')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='byulax.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stats',
            constraint=models.UniqueConstraint(fields=('player_id', 'game_id'), name='game_player_CPK'),
        ),
    ]
