# Generated by Django 4.1.2 on 2022-11-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byulax', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='year_in_school',
            new_name='year',
        ),
        migrations.AddField(
            model_name='stats',
            name='goals_against',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='saves',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Att', 'Attack'), ('Mid', 'Midfield'), ('DM', 'Defensive Midfield'), ('LSM', 'Long Stick Midfield'), ('FOS', 'Face Off Specialist'), ('Def', 'Defenseman'), ('Goal', 'Goalkeeper')], max_length=4),
        ),
    ]
